// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     com/yinhe/android/iptv/UtilityCTC

#ifndef com_yinhe_android_iptv_UtilityCTC_JNI
#define com_yinhe_android_iptv_UtilityCTC_JNI

#include <jni.h>

#include "../../../../../../../../../base/android/jni_generator/jni_generator_helper.h"

#include "base/android/jni_int_wrapper.h"

// Step 1: forward declarations.
namespace {
const char kUtilityCTCClassPath[] = "com/yinhe/android/iptv/UtilityCTC";
// Leaking this jclass as we cannot use LazyInstance from some threads.
base::subtle::AtomicWord g_UtilityCTC_clazz __attribute__((unused)) = 0;
#define UtilityCTC_clazz(env) base::android::LazyGetClass(env, kUtilityCTCClassPath, &g_UtilityCTC_clazz)

}  // namespace

namespace content {
namespace iptv {

// Step 2: method stubs.

static base::subtle::AtomicWord g_UtilityCTC_startLocalCfg = 0;
static jboolean Java_UtilityCTC_startLocalCfg(JNIEnv* env) {
  CHECK_CLAZZ(env, UtilityCTC_clazz(env),
      UtilityCTC_clazz(env), false);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, UtilityCTC_clazz(env),
      "startLocalCfg",

"("
")"
"Z",
      &g_UtilityCTC_startLocalCfg);

  jboolean ret =
      env->CallStaticBooleanMethod(UtilityCTC_clazz(env),
          method_id);
  jni_generator::CheckException(env);
  return ret;
}

// Step 3: RegisterNatives.

}  // namespace iptv
}  // namespace content

#endif  // com_yinhe_android_iptv_UtilityCTC_JNI
