// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     com/yinhe/android/iptv/AuthenticationCTC

#ifndef com_yinhe_android_iptv_AuthenticationCTC_JNI
#define com_yinhe_android_iptv_AuthenticationCTC_JNI

#include <jni.h>

#include "../../../../../../../../../base/android/jni_generator/jni_generator_helper.h"

#include "base/android/jni_int_wrapper.h"

// Step 1: forward declarations.
namespace {
const char kAuthenticationCTCClassPath[] =
    "com/yinhe/android/iptv/AuthenticationCTC";
// Leaking this jclass as we cannot use LazyInstance from some threads.
base::subtle::AtomicWord g_AuthenticationCTC_clazz __attribute__((unused)) = 0;
#define AuthenticationCTC_clazz(env) base::android::LazyGetClass(env, kAuthenticationCTCClassPath, &g_AuthenticationCTC_clazz)

}  // namespace

namespace content {
namespace iptv {

// Step 2: method stubs.

static base::subtle::AtomicWord g_AuthenticationCTC_CTCStartUpdate = 0;
static jboolean Java_AuthenticationCTC_CTCStartUpdate(JNIEnv* env) {
  CHECK_CLAZZ(env, AuthenticationCTC_clazz(env),
      AuthenticationCTC_clazz(env), false);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, AuthenticationCTC_clazz(env),
      "CTCStartUpdate",

"("
")"
"Z",
      &g_AuthenticationCTC_CTCStartUpdate);

  jboolean ret =
      env->CallStaticBooleanMethod(AuthenticationCTC_clazz(env),
          method_id);
  jni_generator::CheckException(env);
  return ret;
}

// Step 3: RegisterNatives.

}  // namespace iptv
}  // namespace content

#endif  // com_yinhe_android_iptv_AuthenticationCTC_JNI
