// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     com/yinhe/android/iptv/HTMLObjectElement

#ifndef com_yinhe_android_iptv_HTMLObjectElement_JNI
#define com_yinhe_android_iptv_HTMLObjectElement_JNI

#include <jni.h>

#include "../../../../../../../../../base/android/jni_generator/jni_generator_helper.h"

#include "base/android/jni_int_wrapper.h"

// Step 1: forward declarations.
namespace {
const char kHTMLObjectElementClassPath[] =
    "com/yinhe/android/iptv/HTMLObjectElement";
// Leaking this jclass as we cannot use LazyInstance from some threads.
base::subtle::AtomicWord g_HTMLObjectElement_clazz __attribute__((unused)) = 0;
#define HTMLObjectElement_clazz(env) base::android::LazyGetClass(env, kHTMLObjectElementClassPath, &g_HTMLObjectElement_clazz)

}  // namespace

namespace content {
namespace iptv {

// Step 2: method stubs.

static base::subtle::AtomicWord g_HTMLObjectElement_bagJson = 0;
static jboolean Java_HTMLObjectElement_bagJson(JNIEnv* env, const
    base::android::JavaRefOrBare<jstring>& params) {
  CHECK_CLAZZ(env, HTMLObjectElement_clazz(env),
      HTMLObjectElement_clazz(env), false);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, HTMLObjectElement_clazz(env),
      "bagJson",

"("
"Ljava/lang/String;"
")"
"Z",
      &g_HTMLObjectElement_bagJson);

  jboolean ret =
      env->CallStaticBooleanMethod(HTMLObjectElement_clazz(env),
          method_id, params.obj());
  jni_generator::CheckException(env);
  return ret;
}

// Step 3: RegisterNatives.

}  // namespace iptv
}  // namespace content

#endif  // com_yinhe_android_iptv_HTMLObjectElement_JNI
